### ISSUE TITLE
Problem installation

### ISSUE THREAD

**Issue by IT4STORES** [tomershvueli/n8n-nodes-apprise#1]
Unable to install package => we got an error message:

Error installing new package
Error loading package "n8n-nodes-apprise":ENOENT: no such file or directory, open '/home/user/.n8n/nodes/node_modules/n8n-nodes-apprise/package.json'

Self-hosted n8n v 0.202.1 with PM2 on Debian 11

**Comment by tomershvueli** [comment]
Quite odd as I followed the n8n-nodes-starter template. Are you able to install other n8n community nodes?

**Comment by IT4STORES** [comment]
Found it => sub-folder /home/user/.n8n/nodes/node_modules was missing.

After creating the missing sub-folder, the installation finished without any error.
